name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    brancers: [ main ]

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: root
          POSTGRES_DB: simple_bank
        option: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.22
      id: go

    - name: Check out code into Go module directory
      uses: actions/checkout@v2

    - name: Run migration
      run: make migrateup

    - name: Test
      run: make test